name: mywealthpath
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas==1.5.3
  - panel==0.14.3
  - numpy==1.24.2
  - hvplot==0.8.2
  - python=3.9.16
  - pip
  - matplotlib==3.7.0
  - bokeh==2.4.3
  - jupyterlab==3.5.0
  - scikit-learn==1.2.2
  - scipy==1.10.1
  - seaborn==0.12.2
  - pip:
      - yahoo-fin==0.8.9.1
      - tensorflow==2.11.1
      - pandas-ta==0.3.14b0
      - keras-tuner==1.3.5

